### ISSUE TITLE
Example of adding Bootstrap4 in the README has drifted

### ISSUE THREAD

**Issue by ctgraham** [Vitaliy-1/JATSParserPlugin#13]
The link in the README:
> it must be added alongside with jQuery from the plugin main class (it is quite straightforward)

should be permalinked to:
https://github.com/Vitaliy-1/JATSParserPlugin/blob/0bfbe3acba6841cbfbec01e220d8ae507cde02af/JatsParserPlugin.inc.php#L145-L148

**Comment by Vitaliy-1** [comment]
Thanks!
