### ISSUE TITLE
Compatibility with OJS 3.2

### ISSUE THREAD

**Issue by Vitaliy-1** [Vitaliy-1/JATSParserPlugin#16]
- [x] fatal error on retrieving ArticleDAO
- [ ] adapt plugin for article versioning 
- [x] undefined method CitationDAO::getBySubmissionId
- [x] adapt plugin to a new publication schema

**Comment by abargouei** [comment]
Thank you @Vitaliy-1 
Is the latest version compatible with OJS 3.2.0.1? If not, which one is compatible with OJS 3.2.0.1?

**Comment by Vitaliy-1** [comment]
@abargouei,

Working on updates, they'll be ready soon

**Comment by abargouei** [comment]
Thanks

**Comment by Vitaliy-1** [comment]
Hi @abargouei,

Can you test the [new release](https://github.com/Vitaliy-1/JATSParserPlugin/releases/tag/2.1.0.0) if it works as expected?

**Comment by abargouei** [comment]
Thanks. JatsParser Plugin is working fine. Awesome! I will put a comment if I face any problem. Thank you so much @Vitaliy-1
