### ISSUE TITLE
delete a HTML and languages support

### ISSUE THREAD

**Issue by carzamora** [Vitaliy-1/JATSParserPlugin#30]
Hi, when I try the plugin (prerelease 2.1.9) it works fine, but I found two issues:

(1) with an article written in Spanish, the HTML file was included in both languages, and
(2) when I delete the XML file, the HTML was not be deleted 

for solve this problem I just disable the plugin, but the plugin is very good and I hope you can improve those things or tell me if you know some solution

Thank you!!

**Comment by Vitaliy-1** [comment]
About the first issue. Did you try to convert 1 file for 2 languages? Can you describe it in more detail? I cannot reproduce the problem locally - if choosing for each locale different files, it doesn't cause problems on my OJS instance (3.2.1).

> when I delete the XML file, the HTML was not be deleted

Yes, this is done deliberately, deleting XML files doesn't remove HTML. HTML full-text can be removed by choosing the `default` option (I'd need to rename it to avoid confusion). Probably, it will also require a workaround for dependent files, e.g. images, like saving them into a separate directory.

**Comment by carzamora** [comment]
Oh, sorry, you are right! I just need one XML in the original language and the other I keep in Default and all is OK now. I don't know what happened before, but with your explanation, I could understand and all is good now! 

Thank you!
