### ISSUE TITLE
Fatal error when installing OJS

### ISSUE THREAD

**Issue by NateWr** [Vitaliy-1/JATSParserPlugin#35]
If the `JATSParserPlugin` files are there in the `plugins/generic` folder when OJS is installed it will cause a fatal error. This is because it tries to access the database before the database exists. The following code is causing the problem:

https://github.com/Vitaliy-1/JATSParserPlugin/blob/master/JatsParserPlugin.inc.php#L33-L37

Either move it out of the register method put it behind a check for `SESSION_DISABLE_INIT`:

```
if (!defined('SESSION_DISABLE_INIT')) {
 ...
}
```

**Comment by Vitaliy-1** [comment]
Thanks! This part of code is unnecessary now as the plugin is not conflicting with Lens for a galley rendering anymore and can be removed. I need to do some refactoring here. This will take some time.

**Comment by Vitaliy-1** [comment]
Fixed as part of the refactoring: https://github.com/Vitaliy-1/JATSParserPlugin/issues/41 and: https://github.com/Vitaliy-1/JATSParserPlugin/issues/39.
