### ISSUE TITLE
DOI link parsed multiple times when using ACM Citation Style

### ISSUE THREAD

**Issue by rahmanramsi** [Vitaliy-1/JATSParserPlugin#63]
![image](https://user-images.githubusercontent.com/48276043/127585618-ff794c66-ac3f-4a33-9084-3fc923806e59.png)

**Comment by Vitaliy-1** [comment]
Hi @rahmanramsi, sorry for that late reply.
Hmm, how do they look in the original JATS XML file? With the prefix or without?

**Comment by Vitaliy-1** [comment]
While exploring I found this related issue: https://github.com/pkp/pkp-lib/issues/3212 (the plugin uses CSL in new versions to format citations)

**Comment by Vitaliy-1** [comment]
@rahmanramsi,

Can you apply the changes in this commit to see whether it solves the issue? https://github.com/Vitaliy-1/JATSParser/commit/de4a9a180bf59c08ba30cec1ce4a354191ea22de

**Comment by rahmanramsi** [comment]
@Vitaliy-1,

Sorry for the late reply, with that commit it solves the issue. Thanks

**Comment by Vitaliy-1** [comment]
Great! Thanks for confirming
