### ISSUE TITLE
Incorrect fileTypes

### ISSUE THREAD

**Issue by sbirAECA** [Vitaliy-1/JATSParserPlugin#64]
Good morning @Vitaliy-1
First of all I would like to thank you for this great plugin that you have developed.
I think there is a little mistake at 'JatsParserPlugin.inc.php' on line 352
Shouldn't it be 'if (!empty($$submissionFilesXML)) {' instead of 'if (!empty($submissionFiles)) {'
Regards
Carlos Martínez

**Comment by Vitaliy-1** [comment]
Thanks, @sbirAECA! You are right, there should be check only for XML and not for all submission files.

**Comment by Vitaliy-1** [comment]
Fixed in the main and stable branch
