### ISSUE TITLE
OJS crashing

### ISSUE THREAD

**Issue by Rhynden** [Vitaliy-1/JATSParserPlugin#65]
Hi,
I succesfully installed and activated the plugin.
Now when I got to my submissions and want to View one, it crashes with the following error:
`PHP Fatal error:  Uncaught TypeError: array_unique(): Argument #1 ($array) must be of type array, null given in C:\Users\flori\Documents\ojs-3_3_0\plugins\generic\jatsParser\JatsPar
serPlugin.inc.php:1001
Stack trace:
#0 C:\Users\flori\Documents\ojs-3_3_0\plugins\generic\jatsParser\JatsParserPlugin.inc.php(1001): array_unique(NULL)
#1 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\classes\plugins\HookRegistry.inc.php(107): JatsParserPlugin->addCitationsFormFields('Form::config::b...', Object(PKP\components\forms\publication\PKPCitationsForm
))
#2 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\classes\components\forms\FormComponent.inc.php(237): HookRegistry::call('Form::config::b...', Object(PKP\components\forms\publication\PKPCitationsForm))
#3 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\pages\workflow\PKPWorkflowHandler.inc.php(324): PKP\components\forms\FormComponent->getConfig()
#4 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\classes\core\PKPRouter.inc.php(395): PKPWorkflowHandler->index(Array, Object(Request))
#5 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\classes\core\PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)
#6 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\classes\core\Dispatcher.inc.php(144): PKPPageRouter->route(Object(Request))
#7 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\classes\core\PKPApplication.inc.php(362): Dispatcher->dispatch(Object(Request))
#8 C:\Users\flori\Documents\ojs-3_3_0\index.php(68): PKPApplication->execute()
#9 {main}
  thrown in C:\Users\flori\Documents\ojs-3_3_0\plugins\generic\jatsParser\JatsParserPlugin.inc.php on line 1001
[Wed Dec 15 13:32:48 2021] [::1]:49413 [500]: GET /index.php/wordtest/workflow/index/2/1 - Uncaught TypeError: array_unique(): Argument #1 ($array) must be of type array, null given in C:\Users\flori\Document
s\ojs-3_3_0\plugins\generic\jatsParser\JatsParserPlugin.inc.php:1001
Stack trace:
#0 C:\Users\flori\Documents\ojs-3_3_0\plugins\generic\jatsParser\JatsParserPlugin.inc.php(1001): array_unique(NULL)
#1 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\classes\plugins\HookRegistry.inc.php(107): JatsParserPlugin->addCitationsFormFields('Form::config::b...', Object(PKP\components\forms\publication\PKPCitationsForm
))
#2 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\classes\components\forms\FormComponent.inc.php(237): HookRegistry::call('Form::config::b...', Object(PKP\components\forms\publication\PKPCitationsForm))
#3 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\pages\workflow\PKPWorkflowHandler.inc.php(324): PKP\components\forms\FormComponent->getConfig()
#4 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\classes\core\PKPRouter.inc.php(395): PKPWorkflowHandler->index(Array, Object(Request))
#5 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\classes\core\PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)
#6 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\classes\core\Dispatcher.inc.php(144): PKPPageRouter->route(Object(Request))
#7 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\classes\core\PKPApplication.inc.php(362): Dispatcher->dispatch(Object(Request))
#8 C:\Users\flori\Documents\ojs-3_3_0\index.php(68): PKPApplication->execute()
#9 {main}
  thrown in C:\Users\flori\Documents\ojs-3_3_0\plugins\generic\jatsParser\JatsParserPlugin.inc.php on line 1001
`
Any suggestions?

**Comment by Vitaliy-1** [comment]
Thanks, @Rhynden!

Can you apply [this commit](https://github.com/Vitaliy-1/JATSParserPlugin/commit/1f000a5ce5e12a7fe82c257223556be551538f19) and check whether the problem persists?

**Comment by Rhynden** [comment]
Hi!
Yes, that seems to have fixed the problem.
Thanks!
