### ISSUE TITLE
File missing - JATSParser/vendor/autoload.php

### ISSUE THREAD

**Issue by geniusdesignbrasil** [Vitaliy-1/JATSParserPlugin#69]
Hi @Vitaliy-1,

I tried to install latest pre-release in an OJS 3.3.0.8 version and some files seems to be missing.

Here it it php log:

PHP Fatal error:  require_once(): Failed opening required './plugins/generic/JATSParserPlugin/JATSParser/vendor/autoload.php' (include_path='.:') in ./plugins/generic/JATSParserPlugin/JatsParserPlugin.inc.php on line 13

JatsParserPlugin.inc.php line 13:
require_once __DIR__ . '**JATSParser/vendor/autoload.php**';

It crashes OJS plugin list page.

I have not found any directory named "vendor" in JatsParser and JatsParserPlugin repositories.

**Comment by Vitaliy-1** [comment]
Hi @geniusdesignbrasil,

Looking at [2.1.9-3 release](https://github.com/Vitaliy-1/JATSParserPlugin/releases/tag/2.1.9.3), it includes autoload file. Are you working with the source code or installing the packed release?

**Comment by geniusdesignbrasil** [comment]
Thank you for your quick response, @Vitaliy-1.

I've downloaded [2.1.9-3 release](https://github.com/Vitaliy-1/JATSParserPlugin/releases/tag/2.1.9.3) zip file. Now checking the tar.gz file I founded vendor directory.

My miss... I will reupload it and validate. Thank you!

**Comment by geniusdesignbrasil** [comment]
@Vitaliy-1,

Everything works fine. I downloaded  the tar.gz file and is complete. I have some new doubts but I will open a new issue.

Ty!
